const items = [
  "High-Speed Stackup",
  "Differential Pair Engine",
  "BGA Fanout & Escape",
  "Impedance Control",
  "Multi-Layer Microvia Array",
  "RF Signal Integrity",
  "Power Distribution Net",
  "FPGA Interconnect",
  "Automated DRC Validation",
  "Thermal Relief Mesh",
  "Rigid-Flex Substrate",
  "High-Density Interconnect",
  "AI Copilot Router",
  "Schematic Topology",
  "Parasitic Extraction",
  "EMI Shielding Matrix",
  "Blind & Buried Vias",
  "Serpentine Tuning",
  "Gerber Layer Synthesis",
  "Component Library AI",
  "Thermal Via Optimization",
];

export default items;
