export const spacesData = [
  {
    id: 1,
    categories: ["High-Speed", "Compute"],
    image: "/spotlight/4.jpg.jpeg",
    date: "June 2025",
    name: "TensorCore Carrier",
    location: "16-Layer High Density Interconnect",
    clientImage: "/spotlight/6.jpg.jpeg",
    clientName: "Aeroflux Robotics",
    route: "/sample-space",
  },
  {
    id: 2,
    categories: ["RF & Wireless", "IoT"],
    image: "/spotlight/4.jpg.jpeg",
    date: "May 2025",
    name: "AeroNode Telemetry",
    location: "6-Layer Impedance Tuned Substrate",
    clientImage: "/spotlight/1.jpg.jpeg",
    clientName: "NovaSat Aerospace",
    route: "/sample-space",
  },
  {
    id: 3,
    categories: ["Power & Flex", "Robotics"],
    image: "/spotlight/5.jpg.jpeg",
    date: "April 2025",
    name: "QuantumDrive ESC",
    location: "4-Layer 4oz Heavy Copper Board",
    clientImage: "/spotlight/5.jpg.jpeg",
    clientName: "Dynasty Dynamics",
    route: "/sample-space",
  },
  {
    id: 4,
    categories: ["High-Speed", "Compute"],
    image: "/spotlight/2.jpg.jpeg",
    date: "March 2025",
    name: "OmniVision FPGA Core",
    location: "12-Layer Microvia BGA Array",
    clientImage: "/spotlight/9.jpg.jpeg",
    clientName: "NeuroPulse Systems",
    route: "/sample-space",
  },
  {
    id: 5,
    categories: ["Power & Flex", "Medical"],
    image: "/spotlight/7.jpg.jpeg",
    date: "February 2025",
    name: "NeuralSense Flex",
    location: "8-Layer Rigid-Flex Sensor Net",
    clientImage: "/spotlight/8.jpg.jpeg",
    clientName: "BioLogic Health",
    route: "/sample-space",
  },
  {
    id: 6,
    categories: ["RF & Wireless", "Compute"],
    image: "/spotlight/2.jpg.jpeg",
    date: "January 2025",
    name: "Gigabit Transceiver Array",
    location: "10-Layer Low-Loss Rogers Substrate",
    clientImage: "/spotlight/9.jpg.jpeg",
    clientName: "Photonix Labs",
    route: "/sample-space",
  },
  {
    id: 7,
    categories: ["High-Speed", "Power & Flex"],
    image: "/spotlight/8.jpg.jpeg",
    date: "December 2024",
    name: "Automotive ECU Master",
    location: "14-Layer AEC-Q200 Qualified",
    clientImage: "/spotlight/2.jpg.jpeg",
    clientName: "Apex Automotive",
    route: "/sample-space",
  },
];
